# Use root/changethis as user/password credentials
version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: dbcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../mysql-data:/var/lib/mysql # wordpress database is nearby.
    ports:
      - 3306:3306 # bind this to docker host to attach an external client.
    environment:
      MYSQL_ROOT_PASSWORD: changethis

  adminer:
    depends_on:
      - db
    image: adminer:4.8.1-standalone
    container_name: adminercontainer
    restart: always
    ports:
      - 8080:8080 # create a database for WordPress before runing installation.


  wordpress:
    depends_on:
      - adminer
    container_name: wpservercontainer
    restart: always
    build:
      dockerfile: ./docker/PhpServerDockerfile
      context: ../
    volumes:
      - ../wordpress-core:/var/www/html
      - ../wp-head-inject-plugin:/var/www/html/wp-content/plugins/wp-head-inject-plugin
      - ../config/wp-config.php:/var/www/html/wp-config.php
      - ../config/phpinfo.php:/var/www/html/phpinfo.php
    ports:
      - 4040:80
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal